insert into hotel (name, city, country, address, brand) values ('ClubCorp Holdings, Inc.', 'Persen', 'Indonesia', '17516 Clarendon Place', 'Garden');
insert into hotel (name, city, country, address, brand) values ('Telephone and Data Systems, Inc.', 'Novopavlovsk', 'Russia', '6 5th Alley', 'Clothing');
insert into hotel (name, city, country, address, brand) values ('Curis, Inc.', 'Neftegorsk', 'Russia', '6276 Lindbergh Point', 'Books');
insert into hotel (name, city, country, address, brand) values ('Cogint, Inc.', 'Qingshanhu', 'China', '1103 Annamark Road', 'Clothing');
insert into hotel (name, city, country, address, brand) values ('Shutterfly, Inc.', 'Chiang Yuen', 'Thailand', '4 Kings Street', 'Grocery');
insert into hotel (name, city, country, address, brand) values ('Lam Research Corporation', 'Beijós', 'Portugal', '98220 Anniversary Circle', 'Industrial');
insert into hotel (name, city, country, address, brand) values ('TravelCenters of America LLC', 'Haiphong', 'Vietnam', '18452 Garrison Junction', 'Toys');
insert into hotel (name, city, country, address, brand) values ('B. Riley Financial, Inc.', 'Balin', 'China', '60826 Drewry Hill', 'Home');
insert into hotel (name, city, country, address, brand) values ('Hertz Global Holdings, Inc', 'Радовиш', 'Macedonia', '61179 Hanover Street', 'Jewelry');
insert into hotel (name, city, country, address, brand) values ('Corcept Therapeutics Incorporated', 'Jiangjia', 'China', '750 Thompson Parkway', 'Music');
insert into hotel (name, city, country, address, brand) values ('Intrepid Potash, Inc', 'Cirangkong', 'Indonesia', '07 Holy Cross Avenue', 'Outdoors');
insert into hotel (name, city, country, address, brand) values ('Harvard Bioscience, Inc.', 'Petiga', 'Indonesia', '5822 Hoard Trail', 'Books');
insert into hotel (name, city, country, address, brand) values ('Allergan plc.', 'Hotonj', 'Bosnia and Herzegovina', '9489 Monica Terrace', 'Industrial');
insert into hotel (name, city, country, address, brand) values ('RenaissanceRe Holdings Ltd.', 'Eido', 'Portugal', '484 Bultman Trail', 'Music');
insert into hotel (name, city, country, address, brand) values ('Prudential Financial, Inc.', 'La Laguna', 'Mexico', '921 Atwood Alley', 'Outdoors');
insert into hotel (name, city, country, address, brand) values ('BancFirst Corporation', 'Futuroscope', 'France', '4 Melrose Pass', 'Jewelry');
insert into hotel (name, city, country, address, brand) values ('Boston Private Financial Holdings, Inc.', 'Zhinvali', 'Georgia', '65 Schiller Lane', 'Shoes');
insert into hotel (name, city, country, address, brand) values ('Avnet, Inc.', 'Paços', 'Portugal', '7 Golf View Center', 'Games');
insert into hotel (name, city, country, address, brand) values ('Crocs, Inc.', 'Skelivka', 'Ukraine', '572 Huxley Hill', 'Grocery');
insert into hotel (name, city, country, address, brand) values ('Kimco Realty Corporation', 'Düsseldorf', 'Germany', '6031 Jenifer Court', 'Garden');
insert into hotel (name, city, country, address, brand) values ('Chuy''s Holdings, Inc.', 'Glória do Goitá', 'Brazil', '8218 Merry Junction', 'Health');
insert into hotel (name, city, country, address, brand) values ('Aqua America, Inc.', 'Maleevsk', 'Kazakhstan', '5663 Linden Street', 'Games');
insert into hotel (name, city, country, address, brand) values ('Barnes Group, Inc.', 'Słubice', 'Poland', '60 Dovetail Lane', 'Books');
insert into hotel (name, city, country, address, brand) values ('STRATS Trust', 'Tayu', 'Indonesia', '97 Commercial Terrace', 'Garden');
insert into hotel (name, city, country, address, brand) values ('Jones Energy, Inc.', 'Kabar Utara', 'Indonesia', '89 Forest Run Crossing', 'Toys');
insert into hotel (name, city, country, address, brand) values ('BWX Technologies, Inc.', 'Jiuquan', 'China', '0 Scoville Court', 'Kids');
insert into hotel (name, city, country, address, brand) values ('GDS Holdings Limited', 'Kawaliwu', 'Indonesia', '73 Brickson Park Pass', 'Kids');
insert into hotel (name, city, country, address, brand) values ('Quanta Services, Inc.', 'Gunungmanik', 'Indonesia', '780 Hanson Pass', 'Kids');
insert into hotel (name, city, country, address, brand) values ('Two River Bancorp', 'Burevestnik', 'Russia', '860 Mockingbird Junction', 'Computers');
insert into hotel (name, city, country, address, brand) values ('Axar Acquisition Corp.', 'Sabhā', 'Libya', '83297 Dapin Drive', 'Books');
insert into hotel (name, city, country, address, brand) values ('Aralez Pharmaceuticals Inc.', 'Włoszczowa', 'Poland', '57 Jana Place', 'Garden');
insert into hotel (name, city, country, address, brand) values ('PICO Holdings Inc.', 'Domašinec', 'Croatia', '1 Declaration Junction', 'Books');
insert into hotel (name, city, country, address, brand) values ('WisdomTree Emerging Markets Corporate Bond Fund', 'La Soledad', 'Mexico', '6 Service Trail', 'Jewelry');
insert into hotel (name, city, country, address, brand) values ('MGM Growth Properties LLC', 'Ush-Tyube', 'Kazakhstan', '4 Dorton Lane', 'Home');
insert into hotel (name, city, country, address, brand) values ('Applied Materials, Inc.', 'Radenka', 'Serbia', '3 Monterey Lane', 'Health');
insert into hotel (name, city, country, address, brand) values ('PowerShares Variable Rate Investment Grade Portfolio', 'Arcachon', 'France', '2 Springs Parkway', 'Books');
insert into hotel (name, city, country, address, brand) values ('RADA Electronic Industries Ltd.', 'Carodok', 'Indonesia', '79905 Spohn Lane', 'Home');
insert into hotel (name, city, country, address, brand) values ('First Financial Bankshares, Inc.', 'Aduo', 'China', '3313 Hanson Court', 'Clothing');
insert into hotel (name, city, country, address, brand) values ('Triangle Capital Corporation', 'Abomey-Calavi', 'Benin', '7 Sunnyside Pass', 'Music');
insert into hotel (name, city, country, address, brand) values ('Grupo Financiero Santander Mexico S.A. B. de C.V.', 'Wenping', 'China', '70141 Evergreen Trail', 'Automotive');
insert into hotel (name, city, country, address, brand) values ('Universal Logistics Holdings, Inc.', 'Bueng Sam Phan', 'Thailand', '3 Dakota Plaza', 'Health');
insert into hotel (name, city, country, address, brand) values ('Quality Care Properties, Inc.', 'Shanguang', 'China', '807 Maple Wood Road', 'Music');
insert into hotel (name, city, country, address, brand) values ('Targa Resources, Inc.', 'Gaoliang', 'China', '38085 Memorial Way', 'Toys');
insert into hotel (name, city, country, address, brand) values ('Summit Therapeutics plc', 'Guyang', 'China', '234 Superior Way', 'Home');
insert into hotel (name, city, country, address, brand) values ('Cornerstone OnDemand, Inc.', 'Brusyliv', 'Ukraine', '89 Duke Court', 'Electronics');
insert into hotel (name, city, country, address, brand) values ('WageWorks, Inc.', 'Uniejów', 'Poland', '10875 Bultman Terrace', 'Beauty');
insert into hotel (name, city, country, address, brand) values ('Summit Materials, Inc.', 'Duhu', 'China', '05356 Westport Place', 'Movies');
insert into hotel (name, city, country, address, brand) values ('Good Times Restaurants Inc.', 'Isiro', 'Democratic Republic of the Congo', '7 North Alley', 'Garden');
insert into hotel (name, city, country, address, brand) values ('Axar Acquisition Corp.', 'Wichita', 'United States', '655 Eagan Terrace', 'Games');
insert into hotel (name, city, country, address, brand) values ('Greenlight Reinsurance, Ltd.', 'Raffingora', 'Zimbabwe', '948 Swallow Place', 'Music');
